builders:
  stormberry:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "analyzeSchema" ]
    build_extensions: { ".dart": ["___"] }
    auto_apply: dependents
    build_to: cache
    runs_before: [":schema", ":session", ":runner"]
  schema:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "buildSchema" ]
    build_extensions: { ".dart": [ ".schema.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before: ["dart_mappable_builder", "freezed", "json_serializable"]
  session:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "buildSessionSchema" ]
    build_extensions: { "$lib$": [ "session.schema.dart" ] }
    auto_apply: dependents # Needs to be enabled manually
    build_to: source
  runner:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "buildRunner" ]
    build_extensions: { ".dart": [ ".schema.json" ] }
    auto_apply: dependents
    build_to: cache
  database_schema:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "buildDatabaseSchema" ]
    build_extensions: { "$lib$": [ "database.schema.dart" ] }
    required_inputs: [ ".schema.json" ]
    auto_apply: none # Needs to be enabled manually
    build_to: source

targets:
  $default:
    builders:
      stormberry:
        generate_for:
          - test/**/*.dart
      stormberry|schema:
        generate_for:
          - test/**/*.dart
      stormberry|runner:
        generate_for:
          - test/**/*.dart
      build_test:test_bootstrap:
        enabled: false
