name: stormberry
description: A strongly-typed postgres ORM to provide easy bindings between your dart classes and postgres database.
version: 0.16.0
repository: https://github.com/schultek/stormberry
issue_tracker: https://github.com/schultek/stormberry/issues
funding:
  - https://github.com/sponsors/schultek

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^8.1.0
  args: ^2.3.1
  build: ^4.0.0
  collection: ^1.16.0
  crypto: ^3.0.2
  dart_style: ^3.0.1
  file: ^7.0.0
  glob: ^2.1.1
  path: ^1.8.2
  postgres: ^3.4.5
  source_gen: ^4.0.0
  yaml: ^3.1.1

dev_dependencies:
  build_resolvers: ^3.0.0
  build_runner: ^2.6.0
  build_test: ^3.3.0
  docker_process: ^1.3.1
  lints: ^5.0.0
  test: ^1.26.0
